### ISSUE TITLE
ISS Reporting year should not necessarily be same as data_timestamp year

### ISSUE THREAD

**Issue by AlexAxthelm** [RMI-PACTA/workflow.factset#18]
In general, the ISS reporting year should lag 1 year behind data timestamp (ex. 2021 for 2022Q4, 2022 for 2023Q2 and 2023Q4)

cc @Antoine-Lalechere, @cjyetman

**Comment by cjyetman** [comment]
For reference, this was "solved" with https://github.com/RMI-PACTA/workflow.data.preparation/pull/68/ but now that the FactSet data extraction is here, you'll probably need something similar here
