### ISSUE TITLE
add other FactSet utilities from pacta.data.preparation

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.factset#26]
There are a few utility scripts in https://github.com/RMI-PACTA/pacta.data.preparation/tree/main/data-raw that can no longer work now that the FactSet database is no longer accessible all the time. I suppose these will need to be integrated here instead? @jdhoffa

**Comment by cjyetman** [comment]
also note: this issue should be taken along with these scripts https://github.com/RMI-PACTA/pacta.data.preparation/issues/170

**Comment by jdhoffa** [comment]
For the record, my approach of how I think this should happen is here:
https://github.com/RMI-PACTA/pacta.data.preparation/issues/321#issuecomment-1916301640

**Comment by AlexAxthelm** [comment]
This is starting to feel like a duplicate of #29, unless there are any pieces other than the classification bridges that I'm missing?

**Comment by cjyetman** [comment]
Technically, this directory contains FactSet based lookup tables beyond sector classifications, so it's no solely about sector classifications, but if the idea is adequately captured/tracked in another issue, I don't mind if you close this and combine with the other.
