### ISSUE TITLE
consider migrating issues from pacta.data.preparation

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.factset#27]
There are a number of open issues related to the FactSet database connection code that was moved here. Unfortunately, I can not easily transfer them because pacta.data.preparation is not currently public. You should consider porting them over.

for example:
https://github.com/RMI-PACTA/pacta.data.preparation/issues/277
https://github.com/RMI-PACTA/pacta.data.preparation/issues/116
https://github.com/RMI-PACTA/pacta.data.preparation/issues/65

I've also been tagging them with `factset` so you can easily search for them with https://github.com/RMI-PACTA/pacta.data.preparation/issues?q=is%3Aopen+is%3Aissue+label%3Afactset

**Comment by AlexAxthelm** [comment]
- [x] https://github.com/RMI-PACTA/pacta.data.preparation/issues/65 -> #31
- [x] https://github.com/RMI-PACTA/pacta.data.preparation/issues/116 -> #30 
- [x] https://github.com/RMI-PACTA/pacta.data.preparation/issues/170 -> #29 
- [x] https://github.com/RMI-PACTA/pacta.data.preparation/issues/277 -> #32
- [x] https://github.com/RMI-PACTA/pacta.data.preparation/issues/321 -> #33, #34, #35

This appears to be all the issues that need to be migrated to this repo. If I missed any, let me know. Closing this issue in favor of all the others
