### ISSUE TITLE
Should this follow the `pacta.*` naming convention?

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.factset#28]
Or perhaps more accurately, is the intention to extract a `pacta.*` R package from this once it is a bit more stable?

**Comment by AlexAxthelm** [comment]
I don't have an intention to extract this more. Overall, the workflow I'm defining here is "prepare data from a factset database for use with `pacta.data.preparation`, which this does (regardless of if it's used in a Docker container or on bare metal).

Move to close this issue, unless there's other points I'm missing?

**Comment by jdhoffa** [comment]
Happy to close this issue!
